POST http://{{hostname}}/api/categories
Content-Type: application/json

{
  "userId": "aaa",
  "ledgerId": "eb90d5bf-fff2-414f-aceb-b732d003cde6",
  "name": "电费"
}

###
GET http://{{hostname}}/api/categories
Accept: application/json

### 某个Category
GET http://{{hostname}}/api/categories/5bde749e-6b31-406f-ac42-8bba3fa21ebd
Accept: application/json

### 某个用户的所有 Category
GET http://{{hostname}}/api/categories?userId=a204fd0b-b1f2-4eba-ac60-1b03cafe311a
Accept: application/json

### 某个用户的所有 Category
GET http://{{hostname}}/api/categories?userId=eb90d5bf-fff2-414f-aceb-b732d003cde6
Accept: application/json

### 某个账本的所有 Category
GET http://{{hostname}}/api/categories?ledgerId=2046d97b-c46a-44b4-b760-a2f618af98cc
Accept: application/json

### 某个账本的所有 Category
GET http://{{hostname}}/api/categories?ledgerId=bede9fc0-3094-49a5-b272-ebfdf9c7b718
Accept: application/json

### 某个账本的所有 Category
GET http://{{hostname}}/api/categories?ledgerId=16a2f3ad-7da7-4ed4-ae3a-e61ac3ced3c9
Accept: application/json
