### ledgerId 不包含，categoryId
POST http://{{hostname}}/api/ledger-entities
Content-Type: application/json

{
  "ledgerId": "2046d97b-c46a-44b4-b760-a2f618af98cc",
  "categoryId": "b331e230-cb78-4cc2-b2ca-db941e9d1636",
  "date": "2022-03-07",
  "amount": 10,
  "remark": "手抓饼"
}

### ledgerId 无效，categoryId 无效
POST http://{{hostname}}/api/ledger-entities
Content-Type: application/json

{
  "ledgerId": "2044d97b-c46a-44b4-b760-a2f618af98cc",
  "categoryId": "5bde889e-6b31-406f-ac42-8bba3fa21ebd",
  "date": "2022-03-07",
  "amount": 10,
  "remark": "手抓饼"
}

### ledgerId 无效，categoryId 有效
POST http://{{hostname}}/api/ledger-entities
Content-Type: application/json

{
  "ledgerId": "2044d97b-c46a-44b4-b760-a2f618af98cc",
  "categoryId": "5bde749e-6b31-406f-ac42-8bba3fa21ebd",
  "date": "2022-03-07",
  "amount": 10,
  "remark": "手抓饼"
}


### ledgerId 有效，categoryId 无效
POST http://{{hostname}}/api/ledger-entities
Content-Type: application/json

{
  "ledgerId": "2046d97b-c46a-44b4-b760-a2f618af98cc",
  "categoryId": "5bde889e-6b31-406f-ac42-8bba3fa21ebd",
  "date": "2022-03-07",
  "amount": 10,
  "remark": "手抓饼"
}

### ledgerId 有效，categoryId 有效
POST http://{{hostname}}/api/ledger-entities
Content-Type: application/json

{
  "ledgerId": "bede9fc0-3094-49a5-b272-ebfdf9c7b718",
  "categoryId": "b331e230-cb78-4cc2-b2ca-db941e9d1636",
  "date": "2022-03-07",
  "amount": -110,
  "remark": "旺仔小馒头"
}

### 查询所有
GET http://{{hostname}}/api/ledger-entities
Accept: application/json

### 查询某个特定的
GET http://{{hostname}}/api/ledger-entities/a8a90001-4554-47a8-bda2-c4cf558e8be3
Accept: application/json

### 查询某个用户的
GET http://{{hostname}}/api/ledger-entities/user?userId=a204fd0b-b1f2-4eba-ac60-1b03cafe311a
Accept: application/json


###
GET http://{{hostname}}/api/categories/2e2a80bd-2f7d-44e0-a7fe-47bb84910daa
Accept: application/json

###
GET http://{{hostname}}/api/categories/
Accept: application/json


