POST http://{{hostname}}/api/ledgers
Content-Type: application/json

{
  "userId": "eb90d5bf-fff2-414f-aceb-b732d003cde6",
  "name": "个人账本"
}

### 获取所有的列表
GET http://{{hostname}}/api/ledgers
Accept: application/json

### 获取A用户的列表
GET http://{{hostname}}/api/ledgers?userId=a204fd0b-b1f2-4eba-ac60-1b03cafe311a
Accept: application/json

### 获取某个用户的列表
GET http://{{hostname}}/api/ledgers?userId=eb90d5bf-fff2-414f-aceb-b732d003cde6
Accept: application/json

### 获取不存在用户的列表
GET http://{{hostname}}/api/ledgers?userId=eb90d5bf-f3f2-414f-aceb-b732d003cde6
Accept: application/json




