spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql.username:libra}
    password: ${mysql.password:123456}
    url: jdbc:mysql://${mysql.hostname:127.0.0.1}:${mysql.port:3306}/${mysql.schema}?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  config:
    activate:
      on-profile: production
