spring:
  config:
    activate:
      on-profile: development
logging:
  level:
    com:
      kuretru:
        web:
          libra:
            mapper: debug
galaxy:
  oauth2:
    client:
      galaxy:
        server-url: http://127.0.0.1:7052
        application-id: 11ec9610244bfe55777c
        application-secret: c973e950-b0fa-11ec-9610-244bfe55777c
