spring:
  jackson:
    mapper:
      sort-properties-alphabetically: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sso.i5zhen.com/application/o/cloud/
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 4
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:libra}
    password: ${MYSQL_PASSWORD:123456}
    url: jdbc:mysql://${MYSQL_HOSTNAME:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:libra}?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    password: ${REDIS_PASSWORD:}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:4}
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
logging:
  level:
    com.kuretru.web.libra.mapper: debug
    com.kuretru.web.libra.metadata.mapper: debug