spring:
  config:
    activate:
      on-profile: stage
  web:
    resources:
      static-locations: file:/web
logging:
  level:
    com:
      kuretru:
        web:
          libra:
            mapper: debug
