spring:
  config:
    activate:
      on-profile: production
    import:
      - optional:file:./libra-fortune-api/src/main/resources/config/application-production-local.yml
  datasource:
    username:
    password:
    url:
  web:
    resources:
      static-locations: file:/web
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
