### list
GET http://{{hostname}}/api/co/ledgers-entries
Accept: application/json

### select by idlp
GET http://{{hostname}}/api/ledgers/a97b67b7-5792-4504-851d-9321fee23eb4
Accept: application/json

###
POST http://{{hostname}}/api/co-ledgers/{ledgerId}/entries/{entryId}
Content-Type: application/json

{
  "entryId": "69c265f2-f9a3-4e81-b701-d4df76e82cdb",
  "userId": "56ec2b77-857f-435c-a44f-f6e74a298e68",
  "amount": "40"
}

###
PUT http://{{hostname}}/api/co-ledgers/{ledgerId}/entries/{entryId}/9489591a-7f69-4498-9c26-d2b091b55b97
Content-Type: application/json

{
  "entryId": "03f5986a-60d2-4035-b097-d06e4869dfb9",
  "userId": "56ec2b77-857f-435c-a44f-f6e74a298e68",
  "amount": "22"
}

### delete by id  还没测试
DELETE http://{{hostname}}/api/system/users/aa344606-e54f-4e36-a444-8711bd3a59df
Accept: application/json