### list
GET http://{{hostname}}/api/co/ledgers-entries
Accept: application/json

### select by idlp
GET http://{{hostname}}/api/ledgers/a97b67b7-5792-4504-851d-9321fee23eb4
Accept: application/json

###
POST http://{{hostname}}/api/co-ledgers/{{ledgerId}}/entries/{{entryId}}/
Content-Type: application/json

{
  "entryId": "a8a35dfb-7486-4ab2-9119-d6fe754933ba",
  "userId": "a7f39ae9-8a75-4914-8737-3f6a979ebb92",
  "amount": "40"
}

###
PUT http://{{hostname}}/api/co-ledgers/{{ledgerId}}/entries/{{entryId}}/2eee02d5-ddbd-4b43-bab4-448774a366a5
Content-Type: application/json

{
  "entryId": "64f43975-c10c-4063-9c00-2d35dfd2a095",
  "userId": "a087c0e3-2577-4a17-b435-7b12f7aa51e0",
  "amount": "220000"
}

### delete by id  还没测试
DELETE http://{{hostname}}/api/co-ledgers/{{ledgerId}}/entries/{{entryId}}/2eee02d5-ddbd-4b43-bab4-448774a366a5
Accept: application/json