### list
GET http://{{hostname}}/api/entry/tags/93f473ff-7eae-45ae-b979-a068ef78cabb
Accept: application/json

### select by id
GET http://{{hostname}}/api/ledgers/a97b67b7-5792-4504-851d-9321fee23eb4
Accept: application/json

###
POST http://{{hostname}}/api/entry/tags
Content-Type: application/json

{
  "entryId": "03f5986a-60d2-4035-b097-d06e4869dfb9",
  "tagId": "fdf3bb17-b9d9-4c6d-af39-e3affcda24d6"
}

###
PUT http://{{hostname}}/api/entry/tags/93f473ff-7eae-45ae-b979-a068ef78cabb
Content-Type: application/json

{
  "entryId": "69c265f2-f9a3-4e81-b701-d4df76e82cdb",
  "tagId": "87058ef5-e20f-49b9-8276-d7d807467d20"
}

###
PUT http://{{hostname}}/api/ledgers/1a2d875c-6b22-446f-a418-06833117eab2
Content-Type: application/json

{
  "name": "qx个人理财账本1",
  "remark": "123456",
  "type": "1",
  "ownerId": "56ec2b77-857f-435c-a44f-f6e74a298e68"
}

### 合作账本修改
PUT http://{{hostname}}/api/ledgers/53ae9625-dfd6-4f4f-ab1c-377d556f184f
Content-Type: application/json

{
  "name": "合作账本2",
  "remark": "123456",
  "type": "1",
  "ownerId": "56ec2b77-857f-435c-a44f-f6e74a298e68"
}

### delete by id  还没测试
DELETE http://{{hostname}}/api/system/users/aa344606-e54f-4e36-a444-8711bd3a59df
Accept: application/json