### list
GET http://{{hostname}}/api/entry/tags/93f473ff-7eae-45ae-b979-a068ef78cabb
Accept: application/json

### select by id
GET http://{{hostname}}/api/ledgers/a97b67b7-5792-4504-851d-9321fee23eb4
Accept: application/json

###
POST http://{{hostname}}/api/entries/{{entryId}}/tags/{{tagId}}/
Content-Type: application/json

{
  "entryId": "491344cf-c021-48af-bb9d-077c47f81fa0",
  "tagId": "ef25a9e0-3d7f-4230-b01d-ed54fe48e34a"
}

### 没有PUT方法！！！！！！不许更新！！！ 加就是加 删就是删

### delete by id  还没测试
DELETE http://{{hostname}}/api/entries/{{entryId}}/tags/{{tagId}}/68a79ceb-1188-4a7b-8a77-13d0fb6ed8d1
Accept: application/json