### list
GET http://{{hostname}}/api/ledger/common/entries
Accept: application/json

### select by id
GET http://{{hostname}}/api/ledger/categories/a97b67b7-5792-4504-851d-9321fee23eb4
Accept: application/json

###
POST http://{{hostname}}/api/ledgers/{ledgerId}/financial/entries
Content-Type: application/json

{
  "ledgerId": "7b5315a5-54ac-44bd-9a23-a6f6fcf61372",
  "date": "2020-03-16",
  "amount": "69",
  "remark": ""
}

###
PUT http://{{hostname}}/api/ledgers/{ledgerId}/financial/entries/a8a35dfb-7486-4ab2-9119-d6fe754933ba
Content-Type: application/json

{
  "ledgerId": "1a2d875c-6b22-446f-a418-06833117eab2",
  "date": "2020-03-16",
  "amount": "10",
  "remark": ""
}

### delete by id  还没测试
DELETE http://{{hostname}}/api/system/users/aa344606-e54f-4e36-a444-8711bd3a59df
Accept: application/json