###
POST http://{{hostname}}/api/ledgers
Content-Type: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}

{
  "name": "合作账本2",
  "remark": "123456",
  "type": "1",
  "ownerId": "025fd39c-b34d-11ec-9c29-bcaec529789d"
}

###
PUT http://{{hostname}}/api/ledgers/a6b02840-d5cd-48cf-aa8c-95e90a65db4c
Content-Type: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}

{
  "id": "a6b02840-d5cd-48cf-aa8c-95e90a65db4c",
  "name": "普通账本1",
  "remark": "123456",
  "type": "1",
  "ownerId": "025fd39c-b34d-11ec-9c29-bcaec529789d"
}

### list
GET http://{{hostname}}/api/ledgers
Accept: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}

### get by id
GET http://{{hostname}}/api/ledgers/a54b45e2-dbec-447e-91fe-6005d9108e01
Accept: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}