### get
GET http://{{hostname}}/api/ledgers/categories/5bde749e-6b31-406f-ac42-8bba3fa21ebd
Accept: application/json

### list
GET http://{{hostname}}/api/ledgers/categories/
Accept: application/json

### list by ledger_id
GET http://{{hostname}}/api/ledgers/categories?ledger_id=16a2f3ad-7da7-4ed4-ae3a-e61ac3ced3c9
Accept: application/json

### create  DTO UUID 问题 去掉uuid上的@size
POST http://{{hostname}}/api/ledgers/categories/
Content-Type: application/json

{
  "ledgerId": "16a2f3ad-7da7-4ed4-ae3a-e61ac3ced3c9",
  "name": "学费"
}

### update
PUT http://{{hostname}}/api/ledgers/categories/153260c6-2468-4538-8f6b-634c139b8f21
Content-Type: application/json

{
  "ledgerId": "16a2f3ad-7da7-4ed4-ae3a-e61ac3ced3c9",
  "name": "零花钱"
}

### delete
DELETE http://{{hostname}}/api/ledgers/categories/fc6d74f9-14c3-4c72-b9c4-323ccfd0263f
Content-Type: application/json
