###
POST http://{{hostname}}/api/ledgers/{{ledgerId}}/categories
Content-Type: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}

{
  "ledgerId": "da573548-efe1-46a9-9b3a-c6a084668a73",
  "name": "da571111"
}

###
PUT http://{{hostname}}/api/ledgers/{{ledgerId}}/categories/81ba5d30-58bf-4fca-bf55-10869ac31c22
Content-Type: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}

{
  "id": "81ba5d30-58bf-4fca-bf55-10869ac31c22",
  "ledgerId": "a6b02840-d5cd-48cf-aa8c-95e90a65db4c",
  "name": "ab6033333"
}

### list by ledgerId
GET http://{{hostname}}/api/ledgers/{{ledgerId}}/categories
Accept: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}

### select by id
GET http://{{hostname}}/api/ledgers/{{ledgerId}}/categories/b22fe802-2d81-49e3-8450-58dc76699aea
Accept: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}


### delete by id  还没测试
DELETE http://{{hostname}}/api/ledgers/{{ledgerId}}/categories/9219cf0d-ab07-4b1a-95c8-6db40638037a
Accept: application/json