### select
GET http://{{hostname}}/api/ledger/tags/
Accept: application/json

### select by id
GET http://{{hostname}}/api/tags/3342605b-faef-45a8-baa4-77f97d08aac7
Accept: application/json

### select by user_id
GET http://{{hostname}}/api/ledger/tags?user_id=a204fd0b-b1f2-4eba-ac60-1b03cafe311a
Accept: application/json

###  user not find
POST http://{{hostname}}/api/ledger/tags
Content-Type: application/json

{
  "userId": "a21fd0b9-b1f2-4eba-ac60-1b03cafe311a",
  "name": "悟真"
}

### 用户存在 / 重复添加
POST http://{{hostname}}/api/ledger/tags
Content-Type: application/json

{
  "userId": "eb90d5bf-fff2-414f-aceb-b732d003cde6",
  "name": "朋友"
}

### update
PUT http://{{hostname}}/api/ledger/tags/a67e23af-8861-477d-ac9a-9ac908877f1b
Content-Type: application/json

{
  "userId": "a204fd0b-b1f2-4eba-ac60-1b03cafe311a",
  "name": "电影"
}


### delete 要联动 entity_tag表格  暂时还没改
DELETE http://{{hostname}}/api/ledgers/categories/a204fd0b-b1f2-4eba-ac60-1b03cafe311a
Content-Type: application/json




