### 新建
POST http://{{hostname}}/api/ledgers/{{ledgerId}}/categories
Content-Type: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}

{
  "ledgerId": "a6b02840-d5cd-48cf-aa8c-95e90a65db4c",
  "name": "A6B01111"
}

### 更新
PUT http://{{hostname}}/api/ledgers/{{ledgerId}}/categories/fb5a01b2-e32e-4985-8dba-8f36afa6fc5b
Content-Type: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}

{
  "id": "fb5a01b2-e32e-4985-8dba-8f36afa6fc5b",
  "ledgerId": "a6b02840-d5cd-48cf-aa8c-95e90a65db4c",
  "name": "ab603544444444"
}

### list by ledgerId
GET http://{{hostname}}/api/ledgers/{{ledgerId}}/categories
Accept: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}

### select by id
GET http://{{hostname}}/api/ledgers/{{ledgerId}}/categories/c31a43f5-7678-4ea5-bb75-c6aa6aebbe0b
Accept: application/json
Access-Token-ID: {{access-token-id}}
Access-Token: {{access-token-secret}}


### delete by id  还没测试
DELETE http://{{hostname}}/api/ledgers/{{ledgerId}}/categories/1ee1cb9e-90f8-4484-a3ac-45dbbd8aec14
Accept: application/json
