### list
GET http://{{hostname}}/api/ledgers
Accept: application/json

### select by id
GET http://{{hostname}}/api/ledgers/a97b67b7-5792-4504-851d-9321fee23eb4
Accept: application/json

###
POST http://{{hostname}}/api/user/tags
Content-Type: application/json

{
  "userId": "56ec2b77-857f-435c-a44f-f6e74a298e68",
  "name": "56ec tag3"
}

###
PUT http://{{hostname}}/api/users/tags/fdf3bb17-b9d9-4c6d-af39-e3affcda24d6
Content-Type: application/json

{
  "userId": "56ec2b77-857f-435c-a44f-f6e74a298e68",
  "name": "56ec2 tag1"
}


### delete by id  / entry 对应的 tag也会删除
DELETE http://{{hostname}}/api/users/tags/87058ef5-e20f-49b9-8276-d7d807467d20
Accept: application/json